HTML/CSS Project #7: Using Bootstrap To Clone The Newsweek Home Page
RailonA/BootStrap-Page-Newsweek pull request #2
Opened 2020-12-03 21:27 UTC by RailonA

We build a clone of newsweek.com's homepage using HTML, CSS, and bootstrap. This page works best using the FireFox or Google chrome browser, assets might look out of place using other browsers or resolutions.

The focus of this branch was to create a responsive website, which should have 3 major breaking points: the first one is supposed to be for mobile displays (max-width: 375px); the second one is for tablets displays (max-width: 768px); and the last one is for laptops/monitors (min-width: 768px);

2020-12-03 23:10 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @ . Thanks for submitting you project!

Great thing this project has and has done well:
:100: Great solid start!
:100: README looks fine

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] Website looks distorted, to solve this create a container or use one that you already have and give it the rule to set a max-width so it will contain elements between the correct width as the original page and margin auto to center that container in the browser independent of the width of the window.
![image](https://user-images.githubusercontent.com/25774518/101096328-0a05b200-3585-11eb-8ee6-cbfe737b9773.png)

- [x] Images look distorted
![image](https://user-images.githubusercontent.com/25774518/101096412-27d31700-3585-11eb-9be2-7b55b61ab8f2.png)

- [ ] In smaller screens the menu, goes down a level and distorts the menu
![image](https://user-images.githubusercontent.com/25774518/101096586-5cdf6980-3585-11eb-9fb1-da2c01d8afe5.png)

- [ ] Menu have a white space to the right
![image](https://user-images.githubusercontent.com/25774518/101096782-ad56c700-3585-11eb-955f-a586e658c42e.png)

- [ ] Magazine don't look as expected
![image](https://user-images.githubusercontent.com/25774518/101096870-d414fd80-3585-11eb-9fda-bec830d0e545.png)

- [ ] Elemenest don't look as original
![image](https://user-images.githubusercontent.com/25774518/101096630-6ec10c80-3585-11eb-899d-65187c093da4.png)

- [ ] Elements don't look as original
![image](https://user-images.githubusercontent.com/25774518/101096692-88faea80-3585-11eb-8359-9a9f545f30eb.png)

- [ ] Navbar has a white space at the right on talet view
![image](https://user-images.githubusercontent.com/25774518/101096994-feff5180-3585-11eb-8a6a-32234f6d398f.png)

- [ ] Navbar doesn't look as expected
![image](https://user-images.githubusercontent.com/25774518/101097029-12122180-3586-11eb-8d9f-f0c8bc00f418.png)

- [ ] Subscribe and Newsletter section doesn't look like original, they are not centered, the inside elements are not centered, and don't look like the original
![image](https://user-images.githubusercontent.com/25774518/101097206-67e6c980-3586-11eb-81c2-700491a3e781.png)

- [ ]  Footer don't look like the original
![image](https://user-images.githubusercontent.com/25774518/101097313-9664a480-3586-11eb-840d-3437b263a5cd.png)

![image](https://user-images.githubusercontent.com/25774518/101097264-7e8d2080-3586-11eb-9a42-3396f09057bf.png)

- [ ] elements should have a space between the image and the text
![image](https://user-images.githubusercontent.com/25774518/101097383-b1371900-3586-11eb-9779-f5ca9588c48f.png)

- [ ] Top stories should come before featured stories on mobile view
![image](https://user-images.githubusercontent.com/25774518/101097460-cdd35100-3586-11eb-8950-d93e659286d5.png)

- [ ] Remove the `.vscode` directory, it is useful for local development but is not necessary for production-ready projects. Only push production-ready files to the repo. Add `.vscode` file to `.gitignore`.

- [ ] The linter are not configured. please check [microverse-linters](https://github.com/microverseinc/linters-config/tree/master/html-css) and set up github actions

- [ ] The project has duplicated stylesheets, on the stylesheets directory and other in assets css directory. Choose the one that the project will use and change/erase the other or assign it to `.gitinore`

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-12-03 23:10 UTC, jubaan commented on index.html
> +
- [x] Remove white spaces from HTML file and maintain consistency of spaces, between sections. [OPTIONAL]

2020-12-03 23:10 UTC, jubaan commented on stylesheets/header.css
> +.nav-header-1{
- [x] Leave only one line between selectors to improve the file and make it look tidy[OPTIONAL]

2020-12-03 23:10 UTC, jubaan commented on index.html
> +                        </ul>
- [ ] these elements, should be links as the original website. the `<ul>` + `<li>` with `<a>` links inside each menu item.

2020-12-03 23:10 UTC, jubaan commented on index.html
> +                        </div>
- [ ] Try to maintain the correct indentation through the whole file. [OPTIONAL]

2020-12-03 23:10 UTC, jubaan commented on index.html
> +    <link rel="stylesheet" href="assets/css/styles.css">
- [ ] Use paths that start with `./`, notice the dot at the beginning.
```
// Bad Paths
<link rel="stylesheet" href="/assets/stylesheets/main.css">
<link rel="stylesheet" href="/assets/js/bootstrap.min.js">
<img src="/imgs/myimage.png">


// Good Paths
<link rel="stylesheet" href="./assets/stylesheets/main.css">
<link rel="stylesheet" href="./assets/js/bootstrap.min.js">
<img src="./imgs/myimage.png">

```
  - notice how the correct paths start with a `./` that marks the current position of the file within the project directory. Without that the browser wont know where the path to the asset should start from.

2020-12-03 23:10 UTC, jubaan commented on index.html
> +    <link rel="stylesheet" href="assets/css/styles.css">
COMMENT: check if the project is using all theses elements, and if erase the ones that are not being used.

2020-12-05 20:32 UTC, mimipeshy commented
### STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hello @RailonA  👋  👋 , good job on working on all the TSE feedback you were given  👏 👏 . However, before we can mark the project as complete let's check on the following

- [ ]  On the tablet view, the debate section overlaps the content above it.  ⬇️ 
![debate](https://user-images.githubusercontent.com/33067256/101262534-9fa16d00-3750-11eb-886b-a12a30cfa415.PNG)

- [ ] The images on the subscribe section on the large view is not similar to the original one. [link](https://www.newsweek.com/)

Original
![ori](https://user-images.githubusercontent.com/33067256/101262736-e774c400-3751-11eb-911f-11192254e004.PNG)

Clone
![subs](https://user-images.githubusercontent.com/33067256/101262746-f196c280-3751-11eb-909e-0a0e6364a85f.PNG)
 

- [ ]  Fix the stylelint and web hint errors in the repo. The stylelint errors can be easily fixed if you run `npx stylelint --fix`. Check on this [link ](https://github.com/microverseinc/linters-config/tree/master/html-css)for configuration.

- [ ] The screenshot link in the README file is broken, kindly fix that.

- [ ]  The README is missing the `Getting Started` section. This section basically contains instructions on how to use your project, Kindly add that. Check out this [link ](https://github.com/microverseinc/readme-template)for reference.



That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to slack me if you have any questions.

2020-12-06 00:22 UTC, RailonA commented
Hello, I have updated all of the requested changes. I have submitted for another code review.

2020-12-06 01:49 UTC, ioilmio requested changes
## Hello @RailonA  @ 👋🏼 
### The project is almost ready just fix this image above the footer for the mobile view:
![image](https://user-images.githubusercontent.com/51195150/101269239-25331600-376d-11eb-84ee-e85f7298be5e.png)

##### Your effort to work also during the weekend is admirable but remember to have the right work/life balance during your journey at Microverse, we acre about you and your success;
After this ask for another (and hopefully last) review

*For any further information slack me @illuminatosalvatore*

2020-12-06 02:53 UTC, RailonA commented
All requested changes have been changed.

2020-12-06 04:22 UTC, mimipeshy commented
### STATUS : APPROVED 🥳  🍾 

Hello @RailonA  👋 👋 , you have done soo well in this project, I have to approve it 👯‍♂️ , congratulations on working this hard! Go ahead and merge. 
Good luck in the next projects ahead 😄 

Regards
Peris Ndanu

2020-12-07 11:43 UTC, merged